### ISSUE TITLE
Workflow needs to use prisma scheme from main

### ISSUE THREAD

**Issue by mdwiltfong** [mdwiltfong/secret-santa#18]
The current workflow uses the prisma schema within the PR. As a result, theoretically someone could rewrite the schema, and if it goes unnoticed it could be merged into main. Particularly if the rewritten schema passes the already existing tests. Here is a possible workflow to circumnavigate this: 

```
name: Pull Request Workflow

on: [pull_request]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main branch
      uses: actions/checkout@v2
      with:
        ref: 'main'
    - name: Save main branch schema
      run: cp path/to/schema.prisma schema-main.prisma

    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Compare schema with main
      run: |
        if ! diff schema-main.prisma path/to/schema.prisma; then
          echo "Schema changes detected!"
          exit 1
        fi

  test:
    needs: check-schema
    runs-on: ubuntu-latest
    steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: npm test

  update-schema:
    if: github.event.label.name == 'schema-change'
    needs: [check-schema]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout PR branch
      uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Update Test Database Schema
      run: |
        # Your command to update the test database schema
        npm run update-schema
```
